global using NetAdvancedShop.Common.Infrastructure.EventBus.Abstractions;
global using NetAdvancedShop.Common.Infrastructure.EventBus.Events;
global using static NetAdvancedShop.Common.Infrastructure.EventBus.InMemoryEventBusSubscriptionsManager;